# yaml-language-server: $schema=https://schema.zeabur.app/template.json
apiVersion: zeabur.com/v1
kind: Template
metadata:
    name: Prometheus + Grafana + Tempo
spec:
    description: Complete observability stack for Fastify (metrics + traces)
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Grafana_icon.svg/1969px-Grafana_icon.svg.png
    variables:
        - key: PUBLIC_DOMAIN
          type: DOMAIN
          name: Domain
          description: The domain name for your Grafana dashboard
    tags:
        - monitoring
        - grafana
        - prometheus
        - tempo
        - opentelemetry
    readme: |
        This template deploys Prometheus, Grafana, and Grafana Tempo for full observability.
        - Prometheus: collects metrics (Fastify via /metrics)
        - Tempo: stores distributed traces from OpenTelemetry
        - Grafana: visualizes everything
    services:
        - name: prometheus
          icon: https://avatars.githubusercontent.com/u/3380462?s=48&v=4
          template: PREBUILT
          spec:
              source:
                  image: prom/prometheus
              ports:
                  - id: web
                    port: 9090
                    type: HTTP
              volumes:
                  - id: data
                    dir: /prometheus
              configs:
                  - path: /etc/prometheus/prometheus.yml
                    template: |
                        global:
                          scrape_interval: 15s
                        scrape_configs:
                          - job_name: 'prometheus'
                            static_configs:
                              - targets: ['localhost:9090']
                          - job_name: 'fastify-backend'
                            static_configs:
                              - targets: ['backend:3000']
                            metrics_path: '/metrics'
                            scrape_interval: 10s
        - name: tempo
          icon: https://grafana.com/static/assets/img/logos/grafana-tempo.svg
          template: PREBUILT
          spec:
              source:
                  image: grafana/tempo
              ports:
                  - id: otlp
                    port: 4318
                    type: HTTP
                  - id: tempoweb
                    port: 3200
                    type: HTTP
              volumes:
                  - id: data
                    dir: /tmp/tempo
              configs:
                  - path: /etc/tempo.yaml
                    template: |
                        server:
                          http_listen_port: 3200
                        distributor:
                          receivers:
                            otlp:
                              protocols:
                                http:
                                grpc:
                        ingester:
                          trace_idle_period: 10s
                          max_block_bytes: 1000000
                          max_block_duration: 5m
                        compactor:
                          compaction:
                            block_retention: 1h
                        storage:
                          trace:
                            backend: local
                            local:
                              path: /tmp/tempo
                    permission: null
                    envsubst: null
        - name: grafana
          icon: https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Grafana_icon.svg/1969px-Grafana_icon.svg.png
          template: PREBUILT
          spec:
              source:
                  image: grafana/grafana
              ports:
                  - id: web
                    port: 3000
                    type: HTTP
              volumes:
                  - id: data
                    dir: /var/lib/grafana
              env:
                  GF_SECURITY_ADMIN_PASSWORD:
                      default: admin
                  GF_SECURITY_ADMIN_USER:
                      default: admin
              configs:
                  - path: /etc/grafana/provisioning/datasources/datasource.yml
                    template: |
                        apiVersion: 1
                        datasources:
                          - name: Prometheus
                            type: prometheus
                            access: proxy
                            orgId: 1
                            url: http://prometheus:9090
                            basicAuth: false
                            isDefault: true
                          - name: Tempo
                            type: tempo
                            access: proxy
                            url: http://tempo:3200
                            basicAuth: false
                            orgId: 1
                    permission: null
                    envsubst: null
          domainKey: PUBLIC_DOMAIN
