packages:
  - frontend
  - backend
  - types

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - msw
  - prisma
  - protobufjs
  - sharp
  - unrs-resolver
