/**
 * Cache key utilities for Redis caching
 * Provides helper functions to generate consistent cache keys and patterns
 */

/**
 * Cache key patterns for different models
 * These patterns match the cache keys generated by prisma-extension-redis
 */
export const CacheKeyPatterns = {
	/** All Event-related cache keys */
	EVENT_ALL: "prisma:event:*",

	/** All Ticket-related cache keys */
	TICKET_ALL: "prisma:ticket:*",

	/** All EventFormFields-related cache keys */
	EVENT_FORM_FIELDS_ALL: "prisma:event_form_fields:*",

	/** All Registration-related cache keys */
	REGISTRATION_ALL: "prisma:registration:*",

	/** All InvitationCode-related cache keys */
	INVITATION_CODE_ALL: "prisma:invitation_code:*",

	/** All Referral-related cache keys */
	REFERRAL_ALL: "prisma:referral:*",

	/** All User-related cache keys */
	USER_ALL: "prisma:user:*",

	/** All cache keys for a specific event ID */
	eventById: (eventId: string) => `prisma:event:*${eventId}*`,

	/** All cache keys for a specific ticket ID */
	ticketById: (ticketId: string) => `prisma:ticket:*${ticketId}*`,

	/** All cache keys for a specific user ID */
	userById: (userId: string) => `prisma:user:*${userId}*`
} as const;

/**
 * Generate cache invalidation config for common scenarios
 */
export const CacheInvalidation = {
	/**
	 * Invalidate all Event caches
	 */
	events: () => ({
		uncacheKeys: [CacheKeyPatterns.EVENT_ALL],
		hasPattern: true
	}),

	/**
	 * Invalidate all Ticket caches
	 */
	tickets: () => ({
		uncacheKeys: [CacheKeyPatterns.TICKET_ALL],
		hasPattern: true
	}),

	/**
	 * Invalidate all EventFormFields caches
	 */
	eventFormFields: () => ({
		uncacheKeys: [CacheKeyPatterns.EVENT_FORM_FIELDS_ALL],
		hasPattern: true
	}),

	/**
	 * Invalidate Event and Ticket caches together
	 * Use when operations affect both models (e.g., creating/updating tickets)
	 */
	eventsAndTickets: () => ({
		uncacheKeys: [CacheKeyPatterns.EVENT_ALL, CacheKeyPatterns.TICKET_ALL],
		hasPattern: true
	}),

	/**
	 * Invalidate Event and EventFormFields caches together
	 * Use when form fields are modified
	 */
	eventsAndFormFields: () => ({
		uncacheKeys: [CacheKeyPatterns.EVENT_ALL, CacheKeyPatterns.EVENT_FORM_FIELDS_ALL],
		hasPattern: true
	}),

	/**
	 * Invalidate caches for a specific event
	 */
	eventById: (eventId: string) => ({
		uncacheKeys: [CacheKeyPatterns.eventById(eventId)],
		hasPattern: true
	}),

	/**
	 * Custom invalidation with specific patterns
	 */
	custom: (patterns: string[]) => ({
		uncacheKeys: patterns,
		hasPattern: true
	})
};
