// this is generated by claude -- idk how it managed to do that but it works -ns
function md5(text: string): string {
	function rotateLeft(value: number, shift: number): number {
		return (value << shift) | (value >>> (32 - shift));
	}

	function addUnsigned(x: number, y: number): number {
		return (x + y) >>> 0;
	}

	function toUtf8(str: string): number[] {
		const utf8: number[] = [];
		for (let i = 0; i < str.length; i++) {
			let charcode = str.charCodeAt(i);
			if (charcode < 0x80) utf8.push(charcode);
			else if (charcode < 0x800) {
				utf8.push(0xc0 | (charcode >> 6), 0x80 | (charcode & 0x3f));
			} else if (charcode < 0xd800 || charcode >= 0xe000) {
				utf8.push(0xe0 | (charcode >> 12), 0x80 | ((charcode >> 6) & 0x3f), 0x80 | (charcode & 0x3f));
			} else {
				i++;
				charcode = 0x10000 + (((charcode & 0x3ff) << 10) | (str.charCodeAt(i) & 0x3ff));
				utf8.push(0xf0 | (charcode >> 18), 0x80 | ((charcode >> 12) & 0x3f), 0x80 | ((charcode >> 6) & 0x3f), 0x80 | (charcode & 0x3f));
			}
		}
		return utf8;
	}

	const x = toUtf8(text);
	const messageLength = x.length;
	const numberOfWords = ((messageLength + 8) >>> 6) + 1;
	const wordArray = new Array(numberOfWords * 16);

	for (let i = 0; i < numberOfWords * 16; i++) {
		wordArray[i] = 0;
	}

	for (let i = 0; i < messageLength; i++) {
		wordArray[i >>> 2] |= x[i] << ((i % 4) * 8);
	}

	wordArray[messageLength >>> 2] |= 0x80 << ((messageLength % 4) * 8);
	wordArray[numberOfWords * 16 - 2] = messageLength * 8;

	let a = 0x67452301;
	let b = 0xefcdab89;
	let c = 0x98badcfe;
	let d = 0x10325476;

	const S11 = 7,
		S12 = 12,
		S13 = 17,
		S14 = 22;
	const S21 = 5,
		S22 = 9,
		S23 = 14,
		S24 = 20;
	const S31 = 4,
		S32 = 11,
		S33 = 16,
		S34 = 23;
	const S41 = 6,
		S42 = 10,
		S43 = 15,
		S44 = 21;

	for (let k = 0; k < numberOfWords * 16; k += 16) {
		const AA = a;
		const BB = b;
		const CC = c;
		const DD = d;

		const FF = (x: number, y: number, z: number) => (x & y) | (~x & z);
		const GG = (x: number, y: number, z: number) => (x & z) | (y & ~z);
		const HH = (x: number, y: number, z: number) => x ^ y ^ z;
		const II = (x: number, y: number, z: number) => y ^ (x | ~z);

		const T = [
			0xd76aa478, 0xe8c7b756, 0x242070db, 0xc1bdceee, 0xf57c0faf, 0x4787c62a, 0xa8304613, 0xfd469501, 0x698098d8, 0x8b44f7af, 0xffff5bb1, 0x895cd7be, 0x6b901122, 0xfd987193, 0xa679438e, 0x49b40821,
			0xf61e2562, 0xc040b340, 0x265e5a51, 0xe9b6c7aa, 0xd62f105d, 0x02441453, 0xd8a1e681, 0xe7d3fbc8, 0x21e1cde6, 0xc33707d6, 0xf4d50d87, 0x455a14ed, 0xa9e3e905, 0xfcefa3f8, 0x676f02d9, 0x8d2a4c8a,
			0xfffa3942, 0x8771f681, 0x6d9d6122, 0xfde5380c, 0xa4beea44, 0x4bdecfa9, 0xf6bb4b60, 0xbebfbc70, 0x289b7ec6, 0xeaa127fa, 0xd4ef3085, 0x04881d05, 0xd9d4d039, 0xe6db99e5, 0x1fa27cf8, 0xc4ac5665,
			0xf4292244, 0x432aff97, 0xab9423a7, 0xfc93a039, 0x655b59c3, 0x8f0ccc92, 0xffeff47d, 0x85845dd1, 0x6fa87e4f, 0xfe2ce6e0, 0xa3014314, 0x4e0811a1, 0xf7537e82, 0xbd3af235, 0x2ad7d2bb, 0xeb86d391
		];

		// Round 1
		a = addUnsigned(a, addUnsigned(addUnsigned(FF(b, c, d), wordArray[k + 0]), T[0]));
		a = addUnsigned(rotateLeft(a, S11), b);
		d = addUnsigned(d, addUnsigned(addUnsigned(FF(a, b, c), wordArray[k + 1]), T[1]));
		d = addUnsigned(rotateLeft(d, S12), a);
		c = addUnsigned(c, addUnsigned(addUnsigned(FF(d, a, b), wordArray[k + 2]), T[2]));
		c = addUnsigned(rotateLeft(c, S13), d);
		b = addUnsigned(b, addUnsigned(addUnsigned(FF(c, d, a), wordArray[k + 3]), T[3]));
		b = addUnsigned(rotateLeft(b, S14), c);
		a = addUnsigned(a, addUnsigned(addUnsigned(FF(b, c, d), wordArray[k + 4]), T[4]));
		a = addUnsigned(rotateLeft(a, S11), b);
		d = addUnsigned(d, addUnsigned(addUnsigned(FF(a, b, c), wordArray[k + 5]), T[5]));
		d = addUnsigned(rotateLeft(d, S12), a);
		c = addUnsigned(c, addUnsigned(addUnsigned(FF(d, a, b), wordArray[k + 6]), T[6]));
		c = addUnsigned(rotateLeft(c, S13), d);
		b = addUnsigned(b, addUnsigned(addUnsigned(FF(c, d, a), wordArray[k + 7]), T[7]));
		b = addUnsigned(rotateLeft(b, S14), c);
		a = addUnsigned(a, addUnsigned(addUnsigned(FF(b, c, d), wordArray[k + 8]), T[8]));
		a = addUnsigned(rotateLeft(a, S11), b);
		d = addUnsigned(d, addUnsigned(addUnsigned(FF(a, b, c), wordArray[k + 9]), T[9]));
		d = addUnsigned(rotateLeft(d, S12), a);
		c = addUnsigned(c, addUnsigned(addUnsigned(FF(d, a, b), wordArray[k + 10]), T[10]));
		c = addUnsigned(rotateLeft(c, S13), d);
		b = addUnsigned(b, addUnsigned(addUnsigned(FF(c, d, a), wordArray[k + 11]), T[11]));
		b = addUnsigned(rotateLeft(b, S14), c);
		a = addUnsigned(a, addUnsigned(addUnsigned(FF(b, c, d), wordArray[k + 12]), T[12]));
		a = addUnsigned(rotateLeft(a, S11), b);
		d = addUnsigned(d, addUnsigned(addUnsigned(FF(a, b, c), wordArray[k + 13]), T[13]));
		d = addUnsigned(rotateLeft(d, S12), a);
		c = addUnsigned(c, addUnsigned(addUnsigned(FF(d, a, b), wordArray[k + 14]), T[14]));
		c = addUnsigned(rotateLeft(c, S13), d);
		b = addUnsigned(b, addUnsigned(addUnsigned(FF(c, d, a), wordArray[k + 15]), T[15]));
		b = addUnsigned(rotateLeft(b, S14), c);

		// Round 2
		a = addUnsigned(a, addUnsigned(addUnsigned(GG(b, c, d), wordArray[k + 1]), T[16]));
		a = addUnsigned(rotateLeft(a, S21), b);
		d = addUnsigned(d, addUnsigned(addUnsigned(GG(a, b, c), wordArray[k + 6]), T[17]));
		d = addUnsigned(rotateLeft(d, S22), a);
		c = addUnsigned(c, addUnsigned(addUnsigned(GG(d, a, b), wordArray[k + 11]), T[18]));
		c = addUnsigned(rotateLeft(c, S23), d);
		b = addUnsigned(b, addUnsigned(addUnsigned(GG(c, d, a), wordArray[k + 0]), T[19]));
		b = addUnsigned(rotateLeft(b, S24), c);
		a = addUnsigned(a, addUnsigned(addUnsigned(GG(b, c, d), wordArray[k + 5]), T[20]));
		a = addUnsigned(rotateLeft(a, S21), b);
		d = addUnsigned(d, addUnsigned(addUnsigned(GG(a, b, c), wordArray[k + 10]), T[21]));
		d = addUnsigned(rotateLeft(d, S22), a);
		c = addUnsigned(c, addUnsigned(addUnsigned(GG(d, a, b), wordArray[k + 15]), T[22]));
		c = addUnsigned(rotateLeft(c, S23), d);
		b = addUnsigned(b, addUnsigned(addUnsigned(GG(c, d, a), wordArray[k + 4]), T[23]));
		b = addUnsigned(rotateLeft(b, S24), c);
		a = addUnsigned(a, addUnsigned(addUnsigned(GG(b, c, d), wordArray[k + 9]), T[24]));
		a = addUnsigned(rotateLeft(a, S21), b);
		d = addUnsigned(d, addUnsigned(addUnsigned(GG(a, b, c), wordArray[k + 14]), T[25]));
		d = addUnsigned(rotateLeft(d, S22), a);
		c = addUnsigned(c, addUnsigned(addUnsigned(GG(d, a, b), wordArray[k + 3]), T[26]));
		c = addUnsigned(rotateLeft(c, S23), d);
		b = addUnsigned(b, addUnsigned(addUnsigned(GG(c, d, a), wordArray[k + 8]), T[27]));
		b = addUnsigned(rotateLeft(b, S24), c);
		a = addUnsigned(a, addUnsigned(addUnsigned(GG(b, c, d), wordArray[k + 13]), T[28]));
		a = addUnsigned(rotateLeft(a, S21), b);
		d = addUnsigned(d, addUnsigned(addUnsigned(GG(a, b, c), wordArray[k + 2]), T[29]));
		d = addUnsigned(rotateLeft(d, S22), a);
		c = addUnsigned(c, addUnsigned(addUnsigned(GG(d, a, b), wordArray[k + 7]), T[30]));
		c = addUnsigned(rotateLeft(c, S23), d);
		b = addUnsigned(b, addUnsigned(addUnsigned(GG(c, d, a), wordArray[k + 12]), T[31]));
		b = addUnsigned(rotateLeft(b, S24), c);

		// Round 3
		a = addUnsigned(a, addUnsigned(addUnsigned(HH(b, c, d), wordArray[k + 5]), T[32]));
		a = addUnsigned(rotateLeft(a, S31), b);
		d = addUnsigned(d, addUnsigned(addUnsigned(HH(a, b, c), wordArray[k + 8]), T[33]));
		d = addUnsigned(rotateLeft(d, S32), a);
		c = addUnsigned(c, addUnsigned(addUnsigned(HH(d, a, b), wordArray[k + 11]), T[34]));
		c = addUnsigned(rotateLeft(c, S33), d);
		b = addUnsigned(b, addUnsigned(addUnsigned(HH(c, d, a), wordArray[k + 14]), T[35]));
		b = addUnsigned(rotateLeft(b, S34), c);
		a = addUnsigned(a, addUnsigned(addUnsigned(HH(b, c, d), wordArray[k + 1]), T[36]));
		a = addUnsigned(rotateLeft(a, S31), b);
		d = addUnsigned(d, addUnsigned(addUnsigned(HH(a, b, c), wordArray[k + 4]), T[37]));
		d = addUnsigned(rotateLeft(d, S32), a);
		c = addUnsigned(c, addUnsigned(addUnsigned(HH(d, a, b), wordArray[k + 7]), T[38]));
		c = addUnsigned(rotateLeft(c, S33), d);
		b = addUnsigned(b, addUnsigned(addUnsigned(HH(c, d, a), wordArray[k + 10]), T[39]));
		b = addUnsigned(rotateLeft(b, S34), c);
		a = addUnsigned(a, addUnsigned(addUnsigned(HH(b, c, d), wordArray[k + 13]), T[40]));
		a = addUnsigned(rotateLeft(a, S31), b);
		d = addUnsigned(d, addUnsigned(addUnsigned(HH(a, b, c), wordArray[k + 0]), T[41]));
		d = addUnsigned(rotateLeft(d, S32), a);
		c = addUnsigned(c, addUnsigned(addUnsigned(HH(d, a, b), wordArray[k + 3]), T[42]));
		c = addUnsigned(rotateLeft(c, S33), d);
		b = addUnsigned(b, addUnsigned(addUnsigned(HH(c, d, a), wordArray[k + 6]), T[43]));
		b = addUnsigned(rotateLeft(b, S34), c);
		a = addUnsigned(a, addUnsigned(addUnsigned(HH(b, c, d), wordArray[k + 9]), T[44]));
		a = addUnsigned(rotateLeft(a, S31), b);
		d = addUnsigned(d, addUnsigned(addUnsigned(HH(a, b, c), wordArray[k + 12]), T[45]));
		d = addUnsigned(rotateLeft(d, S32), a);
		c = addUnsigned(c, addUnsigned(addUnsigned(HH(d, a, b), wordArray[k + 15]), T[46]));
		c = addUnsigned(rotateLeft(c, S33), d);
		b = addUnsigned(b, addUnsigned(addUnsigned(HH(c, d, a), wordArray[k + 2]), T[47]));
		b = addUnsigned(rotateLeft(b, S34), c);

		// Round 4
		a = addUnsigned(a, addUnsigned(addUnsigned(II(b, c, d), wordArray[k + 0]), T[48]));
		a = addUnsigned(rotateLeft(a, S41), b);
		d = addUnsigned(d, addUnsigned(addUnsigned(II(a, b, c), wordArray[k + 7]), T[49]));
		d = addUnsigned(rotateLeft(d, S42), a);
		c = addUnsigned(c, addUnsigned(addUnsigned(II(d, a, b), wordArray[k + 14]), T[50]));
		c = addUnsigned(rotateLeft(c, S43), d);
		b = addUnsigned(b, addUnsigned(addUnsigned(II(c, d, a), wordArray[k + 5]), T[51]));
		b = addUnsigned(rotateLeft(b, S44), c);
		a = addUnsigned(a, addUnsigned(addUnsigned(II(b, c, d), wordArray[k + 12]), T[52]));
		a = addUnsigned(rotateLeft(a, S41), b);
		d = addUnsigned(d, addUnsigned(addUnsigned(II(a, b, c), wordArray[k + 3]), T[53]));
		d = addUnsigned(rotateLeft(d, S42), a);
		c = addUnsigned(c, addUnsigned(addUnsigned(II(d, a, b), wordArray[k + 10]), T[54]));
		c = addUnsigned(rotateLeft(c, S43), d);
		b = addUnsigned(b, addUnsigned(addUnsigned(II(c, d, a), wordArray[k + 1]), T[55]));
		b = addUnsigned(rotateLeft(b, S44), c);
		a = addUnsigned(a, addUnsigned(addUnsigned(II(b, c, d), wordArray[k + 8]), T[56]));
		a = addUnsigned(rotateLeft(a, S41), b);
		d = addUnsigned(d, addUnsigned(addUnsigned(II(a, b, c), wordArray[k + 15]), T[57]));
		d = addUnsigned(rotateLeft(d, S42), a);
		c = addUnsigned(c, addUnsigned(addUnsigned(II(d, a, b), wordArray[k + 6]), T[58]));
		c = addUnsigned(rotateLeft(c, S43), d);
		b = addUnsigned(b, addUnsigned(addUnsigned(II(c, d, a), wordArray[k + 13]), T[59]));
		b = addUnsigned(rotateLeft(b, S44), c);
		a = addUnsigned(a, addUnsigned(addUnsigned(II(b, c, d), wordArray[k + 4]), T[60]));
		a = addUnsigned(rotateLeft(a, S41), b);
		d = addUnsigned(d, addUnsigned(addUnsigned(II(a, b, c), wordArray[k + 11]), T[61]));
		d = addUnsigned(rotateLeft(d, S42), a);
		c = addUnsigned(c, addUnsigned(addUnsigned(II(d, a, b), wordArray[k + 2]), T[62]));
		c = addUnsigned(rotateLeft(c, S43), d);
		b = addUnsigned(b, addUnsigned(addUnsigned(II(c, d, a), wordArray[k + 9]), T[63]));
		b = addUnsigned(rotateLeft(b, S44), c);

		a = addUnsigned(a, AA);
		b = addUnsigned(b, BB);
		c = addUnsigned(c, CC);
		d = addUnsigned(d, DD);
	}

	const toHex = (n: number) => {
		let hex = "";
		for (let i = 0; i < 4; i++) {
			hex += ((n >> (i * 8)) & 0xff).toString(16).padStart(2, "0");
		}
		return hex;
	};

	return toHex(a) + toHex(b) + toHex(c) + toHex(d);
}

export interface GravatarProfile {
	displayName?: string;
	name?: {
		formatted?: string;
		givenName?: string;
		familyName?: string;
	};
	preferredUsername?: string;
}

export async function fetchGravatarName(email: string): Promise<string | null> {
	try {
		const normalizedEmail = email.trim().toLowerCase();
		const hash = md5(normalizedEmail);
		const response = await fetch(`https://gravatar.com/${hash}.json`);

		if (!response.ok) {
			return null;
		}

		const data = await response.json();
		const profile = data.entry?.[0] as GravatarProfile;

		if (!profile) {
			return null;
		}

		return profile.displayName || profile.name?.formatted || profile.preferredUsername || null;
	} catch (error) {
		console.error("Error fetching Gravatar profile:", error);
		return null;
	}
}
